sudo: false
language: go
before_install:
  - go get github.com/mattn/goveralls
matrix:
  include:
    - go: 1.x
      script:
        - go test -v -race ./...
        - $GOPATH/bin/goveralls -service=travis-ci
  fast_finish: true
